In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/Aashrut/Machine-Learning/master/Placement_Data.csv')
x = data.iloc[:, :-2].values
y = data.iloc[:, -1].values
data

ssc_p  hsc_p     hsc_s  degree_p workex  etest_p  mba_p      status  \
0    67.00  91.00  Commerce     58.00     No     55.0  58.80      Placed   
1    79.33  78.33   Science     77.48    Yes     86.5  66.28      Placed   
2    65.00  68.00      Arts     64.00     No     75.0  57.80      Placed   
3    56.00  52.00   Science     52.00     No     66.0  59.43  Not Placed   
4    85.80  73.60  Commerce     73.30     No     96.8  55.50      Placed   
..     ...    ...       ...       ...    ...      ...    ...         ...   
210  80.60  82.00  Commerce     77.60     No     91.0  74.49      Placed   
211  58.00  60.00   Science     72.00     No     74.0  53.62      Placed   
212  67.00  67.00  Commerce     73.00    Yes     59.0  69.72      Placed   
213  74.00  66.00  Commerce     58.00     No     70.0  60.23      Placed   
214  62.00  58.00   Science     53.00     No     89.0  60.22  Not Placed   

       salary  
0    270000.0  
1    200000.0  
2    250000.0  
3         NaN  
4    425000.0  
..        ...  
210  400000.0  
211  275000.0  
212  295000.0  
213  204000.0  
214       NaN  

[215 rows x 9 columns]

Handling Missing Data

In [5]:
from sklearn.impute import SimpleImputer
imputer_y = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_y.fit(y.reshape(-1,1))
y = imputer_y.transform(y.reshape(-1,1))

Encoding categorical data that doesn’t have binary result

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Encoding categorical data that have binary result

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 6] = le.fit_transform(x[:, 6])

Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

Splitting the data into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
x_train

array([[-0.23221018,  0.95008151, -0.85666269, ..., -0.72444647,
        -0.00759213, -1.18014069],
       [-0.23221018, -1.05254128,  1.16732059, ...,  1.38036423,
        -1.29109087, -0.04779991],
       [-0.23221018,  0.95008151, -0.85666269, ...,  1.38036423,
         1.76363613, -0.02030757],
       ...,
       [-0.23221018, -1.05254128,  1.16732059, ..., -0.72444647,
        -0.00759213, -0.48252255],
       [-0.23221018, -1.05254128,  1.16732059, ..., -0.72444647,
         0.25665761,  1.69452718],
       [-0.23221018,  0.95008151, -0.85666269, ...,  1.38036423,
        -1.10234106, -0.16636063]])

In [11]:
x_test

array([[-0.23221018,  0.95008151, -0.85666269,  0.15706399, -0.58251317,
        -0.18663291, -0.72444647,  1.16643172, -1.62689123],
       [-0.23221018,  0.95008151, -0.85666269, -0.02808697,  0.06133451,
         0.90304633,  1.38036423, -0.98909117,  1.27870553],
       [-0.23221018, -1.05254128,  1.16732059,  1.36054521, -0.21460021,
         0.90304633,  1.38036423,  1.80440609,  1.63095114],
       [-0.23221018,  0.95008151, -0.85666269, -0.7686908 , -0.58251317,
        -1.41252206, -0.72444647, -1.29109087, -0.75229114],
       [-0.23221018,  0.95008151, -0.85666269, -0.21323793,  0.79716044,
         0.35820671,  1.38036423, -0.00759213,  0.40926025],
       [-0.23221018, -1.05254128,  1.16732059, -1.50929463, -1.13438262,
        -0.73147253, -0.72444647, -0.91359124, -0.28148481],
       [-0.23221018,  0.95008151, -0.85666269, -1.78702107, -1.41031735,
        -1.14010225,  1.38036423, -0.91359124, -0.59936499],
       [-0.23221018,  0.95008151, -0.85666269, -0.25026812,  1

In [12]:
y_train

array([[288655.40540541],
       [300000.        ],
       [420000.        ],
       [225000.        ],
       [400000.        ],
       [220000.        ],
       [285000.        ],
       [240000.        ],
       [240000.        ],
       [360000.        ],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [236000.        ],
       [275000.        ],
       [288655.40540541],
       [260000.        ],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [240000.        ],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [288655.40540541],
       [300000.        ],
       [350000.        ],
       [288655.40540541],
       [288655.40540541],
       [380000.        ],
       [233000.        ],
       [288655.40540541],
       [250000.        ],
       [288655.40540541],
       [2300

In [13]:
y_test

array([[300000.        ],
       [295000.        ],
       [250000.        ],
       [220000.        ],
       [200000.        ],
       [288655.40540541],
       [288655.40540541],
       [218000.        ],
       [210000.        ],
       [220000.        ],
       [288655.40540541],
       [250000.        ],
       [288655.40540541],
       [288655.40540541],
       [275000.        ],
       [288655.40540541],
       [290000.        ],
       [288655.40540541],
       [340000.        ],
       [275000.        ],
       [252000.        ],
       [260000.        ],
       [288655.40540541],
       [288655.40540541],
       [360000.        ],
       [400000.        ],
       [288655.40540541],
       [300000.        ],
       [288655.40540541],
       [690000.        ],
       [300000.        ],
       [220000.        ],
       [250000.        ],
       [264000.        ],
       [250000.        ],
       [400000.        ],
       [288655.40540541],
       [200000.        ],
       [2760