In [2]:
import pandas as pd
data=pd.read_csv("C:\\2 ND YEAR\\PROJECTS\\AI FOR DS PROJECT\\AI FOR DS PROJECT\\DATASET2\\ethereum.csv")

In [3]:
data

Date     Open     High      Low    Close  Volume Currency
0     2016-03-10    11.20    11.85    11.07    11.75       4      USD
1     2016-03-11    11.75    11.95    11.75    11.95     179      USD
2     2016-03-12    11.95    13.45    11.95    12.92     833      USD
3     2016-03-13    12.92    15.07    12.92    15.07    1295      USD
4     2016-03-14    15.07    15.07    11.40    12.50   92183      USD
...          ...      ...      ...      ...      ...     ...      ...
2118  2021-12-27  4062.02  4125.22  4033.04  4036.24  313319      USD
2119  2021-12-28  4036.86  4036.86  3760.86  3791.69  527234      USD
2120  2021-12-29  3792.95  3825.97  3607.20  3627.93  456030      USD
2121  2021-12-30  3629.33  3767.93  3589.64  3709.57  355717      USD
2122  2021-12-31  3709.38  3812.01  3623.74  3677.85  405653      USD

[2123 rows x 7 columns]

In [4]:
data5=data[-5:]

In [5]:
data5

Date     Open     High      Low    Close  Volume Currency
2118  2021-12-27  4062.02  4125.22  4033.04  4036.24  313319      USD
2119  2021-12-28  4036.86  4036.86  3760.86  3791.69  527234      USD
2120  2021-12-29  3792.95  3825.97  3607.20  3627.93  456030      USD
2121  2021-12-30  3629.33  3767.93  3589.64  3709.57  355717      USD
2122  2021-12-31  3709.38  3812.01  3623.74  3677.85  405653      USD

In [6]:
datadate=data["Date"]
datadate

0       2016-03-10
1       2016-03-11
2       2016-03-12
3       2016-03-13
4       2016-03-14
           ...    
2118    2021-12-27
2119    2021-12-28
2120    2021-12-29
2121    2021-12-30
2122    2021-12-31
Name: Date, Length: 2123, dtype: object

In [8]:
datainfo=data["Date","Open"]
datainfo

KeyError: ('Date', 'Open')

In [10]:
datainfo=data["Open"]
datainfo

0         11.20
1         11.75
2         11.95
3         12.92
4         15.07
         ...   
2118    4062.02
2119    4036.86
2120    3792.95
2121    3629.33
2122    3709.38
Name: Open, Length: 2123, dtype: float64

In [18]:
for i in datainfo:
    if(i==11.20):
        print (index(i))

NameError: name 'index' is not defined

In [22]:
ALLRows = csv.reader(data, delimiter=',')
for row in ALLRows:
    rows.append(row)
    print(row[1][1])

NameError: name 'csv' is not defined

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
data = np.array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])
#slicing
print(data[:3])
print(data[::-1])

11
55
[11 22 33]
[55 44 33 22 11]


In [3]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])
print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape)  
out_arr = np.squeeze(in_arr) 
print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape) 

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


In [4]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)    
print(a) 

<class 'numpy.ndarray'>
(3,)
[1 2 3]


In [10]:
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)  

5 2 3
[5 2 3]


In [8]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [19]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
data=pd.read_csv("https://raw.githubusercontent.com/Aashrut/Machine-Learning/master/Placement_Data.csv")
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values


In [20]:
x


array([[67.0, 91.0, 'Commerce', ..., 55.0, 58.8, 'Placed'],
       [79.33, 78.33, 'Science', ..., 86.5, 66.28, 'Placed'],
       [65.0, 68.0, 'Arts', ..., 75.0, 57.8, 'Placed'],
       ...,
       [67.0, 67.0, 'Commerce', ..., 59.0, 69.72, 'Placed'],
       [74.0, 66.0, 'Commerce', ..., 70.0, 60.23, 'Placed'],
       [62.0, 58.0, 'Science', ..., 89.0, 60.22, 'Not Placed']],
      dtype=object)

In [21]:
y

array([270000., 200000., 250000.,     nan, 425000.,     nan,     nan,
       252000., 231000.,     nan, 260000., 250000.,     nan, 218000.,
           nan, 200000., 300000.,     nan,     nan, 236000., 265000.,
       393000., 360000., 300000., 360000.,     nan, 240000., 265000.,
       350000.,     nan, 250000.,     nan, 278000., 260000.,     nan,
       300000.,     nan, 320000., 240000., 411000., 287000.,     nan,
           nan, 300000., 200000.,     nan,     nan, 204000., 250000.,
           nan, 200000.,     nan,     nan, 450000., 216000., 220000.,
       240000., 360000., 268000., 265000., 260000., 300000., 240000.,
           nan, 240000.,     nan, 275000., 275000.,     nan, 275000.,
       360000., 240000., 240000., 218000., 336000.,     nan, 230000.,
       500000., 270000.,     nan, 240000., 300000.,     nan, 300000.,
       300000., 400000., 220000.,     nan, 210000., 210000., 300000.,
           nan, 230000.,     nan, 260000., 420000., 300000.,     nan,
       220000.,     

In [23]:
from sklearn.impute import SimpleImputer
imputer_y = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_y.fit(y.reshape(-1,1))
y = imputer_y.transform(y.reshape(-1,1))
y

array([[270000.        ],
       [200000.        ],
       [250000.        ],
       [288655.40540541],
       [425000.        ],
       [288655.40540541],
       [288655.40540541],
       [252000.        ],
       [231000.        ],
       [288655.40540541],
       [260000.        ],
       [250000.        ],
       [288655.40540541],
       [218000.        ],
       [288655.40540541],
       [200000.        ],
       [300000.        ],
       [288655.40540541],
       [288655.40540541],
       [236000.        ],
       [265000.        ],
       [393000.        ],
       [360000.        ],
       [300000.        ],
       [360000.        ],
       [288655.40540541],
       [240000.        ],
       [265000.        ],
       [350000.        ],
       [288655.40540541],
       [250000.        ],
       [288655.40540541],
       [278000.        ],
       [260000.        ],
       [288655.40540541],
       [300000.        ],
       [288655.40540541],
       [320000.        ],
       [2400

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
x

array([[0.0, 1.0, 0.0, ..., 55.0, 58.8, 'Placed'],
       [0.0, 0.0, 1.0, ..., 86.5, 66.28, 'Placed'],
       [1.0, 0.0, 0.0, ..., 75.0, 57.8, 'Placed'],
       ...,
       [0.0, 1.0, 0.0, ..., 59.0, 69.72, 'Placed'],
       [0.0, 1.0, 0.0, ..., 70.0, 60.23, 'Placed'],
       [0.0, 0.0, 1.0, ..., 89.0, 60.22, 'Not Placed']], dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 6] = le.fit_transform(x[:, 6])
x

array([[0.0, 1.0, 0.0, ..., 55.0, 58.8, 'Placed'],
       [0.0, 0.0, 1.0, ..., 86.5, 66.28, 'Placed'],
       [1.0, 0.0, 0.0, ..., 75.0, 57.8, 'Placed'],
       ...,
       [0.0, 1.0, 0.0, ..., 59.0, 69.72, 'Placed'],
       [0.0, 1.0, 0.0, ..., 70.0, 60.23, 'Placed'],
       [0.0, 0.0, 1.0, ..., 89.0, 60.22, 'Not Placed']], dtype=object)

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [29]:
x_train


array([[0.0, 1.0, 0.0, ..., 72.0, 55.41, 'Not Placed'],
       [0.0, 0.0, 1.0, ..., 55.0, 62.0, 'Placed'],
       [0.0, 1.0, 0.0, ..., 95.46, 62.16, 'Placed'],
       ...,
       [0.0, 0.0, 1.0, ..., 72.0, 59.47, 'Placed'],
       [0.0, 0.0, 1.0, ..., 75.5, 72.14, 'Not Placed'],
       [0.0, 1.0, 0.0, ..., 57.5, 61.31, 'Placed']], dtype=object)

In [30]:
x_test

array([[0.0, 1.0, 0.0, 69.0, 60.0, 65.0, 0, 87.55, 52.81, 'Placed'],
       [0.0, 1.0, 0.0, 67.0, 67.0, 73.0, 1, 59.0, 69.72, 'Placed'],
       [0.0, 0.0, 1.0, 82.0, 64.0, 73.0, 1, 96.0, 71.77, 'Placed'],
       [0.0, 1.0, 0.0, 59.0, 60.0, 56.0, 0, 55.0, 57.9, 'Placed'],
       [0.0, 1.0, 0.0, 65.0, 75.0, 69.0, 1, 72.0, 64.66, 'Placed'],
       [0.0, 0.0, 1.0, 51.0, 54.0, 61.0, 0, 60.0, 60.64, 'Not Placed'],
       [0.0, 1.0, 0.0, 48.0, 51.0, 58.0, 1, 60.0, 58.79, 'Not Placed'],
       [0.0, 1.0, 0.0, 64.6, 83.83, 71.72, 0, 86.0, 59.75, 'Placed'],
       [0.0, 1.0, 0.0, 74.0, 73.0, 73.0, 1, 80.0, 67.69, 'Placed'],
       [0.0, 1.0, 0.0, 77.0, 70.0, 59.0, 1, 58.0, 54.43, 'Placed'],
       [0.0, 0.0, 1.0, 67.0, 63.0, 64.0, 0, 60.0, 61.87, 'Not Placed'],
       [0.0, 1.0, 0.0, 64.0, 73.5, 73.0, 0, 52.0, 56.7, 'Placed'],
       [0.0, 1.0, 0.0, 52.0, 64.0, 61.0, 0, 55.0, 62.93, 'Not Placed'],
       [0.0, 1.0, 0.0, 58.0, 70.0, 61.0, 0, 54.0, 52.21, 'Not Placed'],
       [0.0, 1.0, 0.0, 80.9