Shaping & Reshaping of Numpy Array , Expanding & Squeezing of a Numpy Array , Indexing and slicing of a numpy array

Reshape:

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Indexing & Slicing:

In [4]:
data = np.array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])
#slicing
print(data[:3])
print(data[::-1])

11
55
[11 22 33]
[55 44 33 22 11]


Squeezing :

In [5]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])
print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape)  
out_arr = np.squeeze(in_arr) 
print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape) 

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)
